[package]
name = "ark-kzg"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-poly-commit = "0.5.0"
ark-ec = "0.5.0"
ark-poly = "0.5.0"
ark-bls12-381 = "0.5.0"
ark-std = "0.5.0"
rand_core = "0.6.4"
